CREATE TABLE payment_users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(12) NOT NULL UNIQUE,
    account_balance DECIMAL(19, 4) NOT NULL CHECK (account_balance >= 0.00),
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE TABLE payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount DECIMAL(19, 4) NOT NULL CHECK (amount >= 0.00),
    is_success BOOLEAN NOT NULL,
    payment_type ENUM('DIRECT', 'GATEWAY') NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES payment_users(id) ON DELETE CASCADE
);
